development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: development_jgw_core
  pool: 5
  username: joruri
  password: pass
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_jgw_core
  pool: 5
  username: joruri
  password: pass
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: production_jgw_core
  pool: 5
  username: joruri
  password: pass
  socket: /var/lib/mysql/mysql.sock

#Railsの実行環境がproductionの場合、データベース名は下記のようにしてください。
#production_jgw_gw
dev_jgw_gw:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: development_jgw_gw
  pool: 5
  username: joruri
  password: pass
  socket: /var/lib/mysql/mysql.sock

#Railsの実行環境がproductionの場合、データベース名は下記のようにしてください。
#production_jgw_gw_pref
gwsub:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: development_jgw_gw_pref
  pool: 5
  username: joruri
  password: pass
  socket: /var/lib/mysql/mysql.sock
