development:
#  host: 192.168.32.197
  host: 192.168.32.219
  port: 389
  base: dc=pref,dc=tokushima,dc=jp

test:
  host: 192.168.32.219
  port: 389
  base: dc=pref,dc=tokushima,dc=jp

production:
  host: 
  port: 
  base: 
